### ISSUE TITLE
How do I remove a value from cache?

### ISSUE THREAD

**Issue by henrikekblad** [groupon/node-cached#25]
The documentation isn'r really clear on this...

Is it enough to do a ``` set(key, undefined)``` ?

**Comment by jkrems** [comment]
Had to double-check - the second sentence of the README is (emphasis mine):

> The interface only exposes very limited functionality, **there's no** multi-get or **deletion of cached data**.

In other words: We haven't implemented any active removal of data from the cache, cached data can only be replaced or expire naturally. We generally use this library for read-through caching (or rather refresh-ahead caching (?)), so we rarely have the need for messing with the keys directly.

But I'd be happy to review a PR adding support for deletion.
