### ISSUE TITLE
Update docs or change default backend from "noop"

### ISSUE THREAD

**Issue by emertechie** [groupon/node-cached#37]
Just started using library today (mainly the `getOrElse` fn) and couldn't figure out for _ages_ why it kept calling my store and not caching things. I ended up having to dig through the code to eventually discover that the default backend is noop :/

You might want to update the first Usage example you show to call this out. Or, maybe even throw exception is you don't explicitly select a backend.

Thanks for the project

**Comment by jkrems** [comment]
Thanks! That's definitely a good point. Deprecating the `noop` default sounds like a pretty great idea. Not sure when I/we'd come around to it though. :( If you'd be interested, a PR would be appreciated!

**Comment by aaarichter** [comment]
@jkrems I'll remove `noop` in my major bump https://github.com/groupon/node-cached/pull/48
